// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function NowTimestamp() {
  return window['go']['main']['App']['NowTimestamp']();
}

export function OpenTextFile() {
  return window['go']['main']['App']['OpenTextFile']();
}

export function ReorderConnections(arg1) {
  return window['go']['main']['App']['ReorderConnections'](arg1);
}

export function SaveAsTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveAsTextFile'](arg1, arg2);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveTextFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2, arg3);
}
