// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteConnection(arg1:string):Promise<void>;

export function ListConnections():Promise<Array<main.Connection>>;

export function NowTimestamp():Promise<string>;

export function OpenTextFile():Promise<main.OpenResult>;

export function ReorderConnections(arg1:Array<string>):Promise<void>;

export function SaveAsTextFile(arg1:string,arg2:string):Promise<string>;

export function SaveConnection(arg1:main.Connection):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string,arg3:string):Promise<void>;
