// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['SSHManager']['CloseSession'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['SSHManager']['Connect'](arg1);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['main']['SSHManager']['Resize'](arg1, arg2, arg3);
}

export function SftpDownload(arg1, arg2) {
  return window['go']['main']['SSHManager']['SftpDownload'](arg1, arg2);
}

export function SftpList(arg1, arg2) {
  return window['go']['main']['SSHManager']['SftpList'](arg1, arg2);
}

export function SftpMkdir(arg1, arg2) {
  return window['go']['main']['SSHManager']['SftpMkdir'](arg1, arg2);
}

export function SftpReadFile(arg1, arg2) {
  return window['go']['main']['SSHManager']['SftpReadFile'](arg1, arg2);
}

export function SftpRemove(arg1, arg2, arg3) {
  return window['go']['main']['SSHManager']['SftpRemove'](arg1, arg2, arg3);
}

export function SftpRename(arg1, arg2, arg3) {
  return window['go']['main']['SSHManager']['SftpRename'](arg1, arg2, arg3);
}

export function SftpUpload(arg1, arg2) {
  return window['go']['main']['SSHManager']['SftpUpload'](arg1, arg2);
}

export function SftpWriteFile(arg1, arg2, arg3) {
  return window['go']['main']['SSHManager']['SftpWriteFile'](arg1, arg2, arg3);
}

export function Write(arg1, arg2) {
  return window['go']['main']['SSHManager']['Write'](arg1, arg2);
}
