// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function Connect(arg1:main.Connection):Promise<string>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SftpDownload(arg1:string,arg2:string):Promise<string>;

export function SftpList(arg1:string,arg2:string):Promise<Array<main.SftpEntry>>;

export function SftpMkdir(arg1:string,arg2:string):Promise<void>;

export function SftpReadFile(arg1:string,arg2:string):Promise<string>;

export function SftpRemove(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SftpRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpUpload(arg1:string,arg2:string):Promise<number>;

export function SftpWriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Write(arg1:string,arg2:string):Promise<void>;
